on: [push]

name: WebDriver
env:
  EDGE_VERSION: 138.0.3351.55

jobs:
  test:
    name: WebDriverIO Test Runner
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: Setup Microsoft C++ Build Tools
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cargo build
        run: cargo build --release

      - name: Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: npm install
        run: npm install --frozen-lockfile

      - name: Install Edge WebView2
        run: winget install --id=Microsoft.EdgeWebView2Runtime --silent -v ${{ env.EDGE_VERSION }} -e --accept-package-agreements --accept-source-agreements --disable-interactivity

      - name: Install Edge WebDriver
        run: winget install --id=Microsoft.EdgeDriver --silent -v ${{ env.EDGE_VERSION }} -e --accept-package-agreements --accept-source-agreements --disable-interactivity

      - name: Install tauri-driver
        run: cargo install tauri-driver --locked

      - name: Install wait-on
        run: npm add -g wait-on

      - name: Start tauri-driver
        shell: pwsh
        run: |
          Start-Process tauri-driver -ArgumentList '--port', '4444'
          npx wait-on tcp:4444

      - name: WebdriverIO
        run: npm test
